# Generated by Django 5.1.3 on 2024-11-08 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proyecto', models.CharField(max_length=255)),
                ('descripcion_proyecto', models.TextField()),
                ('fecha_inicio_proyecto', models.DateField()),
                ('fecha_fin_proyecto', models.DateField()),
                ('estado_proyecto', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rol', models.CharField(max_length=100)),
                ('descripcion_rol', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sprint', models.CharField(max_length=255)),
                ('fecha_inicio_sprint', models.DateField()),
                ('fecha_fin_sprint', models.DateField()),
                ('estado_sprint', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tarea', models.CharField(max_length=255)),
                ('estado_tarea', models.CharField(max_length=50)),
                ('fecha_creacion_tarea', models.DateField()),
                ('fecha_entrega_tarea', models.DateField()),
                ('descripcion_tarea', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EquipoTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_equipo', models.CharField(max_length=255)),
                ('descripcion_equipo', models.TextField()),
                ('id_proyecto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.proyecto')),
                ('rol_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.roles')),
            ],
        ),
        migrations.AddField(
            model_name='proyecto',
            name='id_sprint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.sprint'),
        ),
        migrations.AddField(
            model_name='sprint',
            name='id_tarea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.tarea'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.usuario'),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido_comentario', models.TextField()),
                ('fecha_comentario', models.DateField()),
                ('id_tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.tarea')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioEquipo',
            fields=[
                ('usuario_equipo_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_union', models.DateField()),
                ('rol_equipo', models.CharField(max_length=100)),
                ('id_equipo_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.equipotrabajo')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.usuario')),
            ],
        ),
    ]
